[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  tommag/TMC5160@^1.1.0
  hideakitai/ArxTypeTraits@^0.3.2

lib_compat_mode = strict
lib_ldf_mode = chain+
